--- #YAML:1.0
name:                Module-CoreList
version:             2.11
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32_01
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
