--- #YAML:1.0
name: Module-CoreList
version: 1.95
author:
  - Richard Clamp E<lt>richardc@unixbeard.netE<gt>
abstract: what modules shipped with versions of perl
license: perl
requires:
  Module::Build: 0.18
  Test::More: 0
provides:
  Module::CoreList:
    file: lib/Module/CoreList.pm
    version: 1.95
generated_by: Module::Build version 0.25
